-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 01:45:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `IdUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `EMail` VARCHAR(1000) NOT NULL,
  `Password` VARCHAR(10) NOT NULL,
  `RegisterDate` DATETIME NOT NULL,
  `UpdateDate` DATETIME NULL,
  `Active` BIT(1) NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `IdProduct` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `RegisterDate` DATETIME NOT NULL,
  `UpdateDate` DATETIME NULL,
  `Active` BIT(1) NULL,
  PRIMARY KEY (`IdProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `IdInventory` INT NOT NULL AUTO_INCREMENT,
  `IdUser` INT NOT NULL,
  `IdProduct` INT NOT NULL,
  `Quantity` INT NOT NULL DEFAULT 0,
  `RegisterDate` DATETIME NOT NULL,
  `UpdateDate` DATETIME NULL,
  `Active` BIT(1) NULL,
  PRIMARY KEY (`IdInventory`),
  INDEX `fk_Inventory_User_idx` (`IdUser` ASC),
  INDEX `fk_Inventory_Product1_idx` (`IdProduct` ASC),
  CONSTRAINT `fk_Inventory_User`
    FOREIGN KEY (`IdUser`)
    REFERENCES `mydb`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventory_Product1`
    FOREIGN KEY (`IdProduct`)
    REFERENCES `mydb`.`Product` (`IdProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
